export const products = [
  // Kundan Products
  {
    id: "k-necklace-rani-haar",
    name: "Kundan Rani Haar",
    price: "$250",
    category: "Necklace",
    subcategory: "Rani Haar",
    images: [
      "https://via.placeholder.com/300?text=Kundan+Rani+Haar+1",
      "https://via.placeholder.com/300?text=Kundan+Rani+Haar+2",
      "https://via.placeholder.com/300?text=Kundan+Rani+Haar+3",
    ],
    hoverImg: "https://via.placeholder.com/300/FF677D?text=Kundan+Rani+Haar+Hover",
    description: "Traditional Kundan Rani Haar for royal occasions.",
    colors: ["#FF677D", "#D9BF77"],
  },
  {
    id: "k-earrings-chandbalis",
    name: "Kundan Chandbalis",
    price: "$170",
    category: "Earrings",
    subcategory: "Chandbalis",
    images: [
      "https://via.placeholder.com/300?text=Kundan+Chandbalis+1",
      "https://via.placeholder.com/300?text=Kundan+Chandbalis+2",
      "https://via.placeholder.com/300?text=Kundan+Chandbalis+3",
    ],
    hoverImg: "https://via.placeholder.com/300/FFB3BA?text=Kundan+Chandbalis+Hover",
    description: "Elegant Kundan Chandbalis for festive occasions.",
    colors: ["#FFB3BA", "#6A0572"],
  },
  {
    id: "k-rings-cocktail",
    name: "Kundan Cocktail Ring",
    price: "$120",
    category: "Rings",
    subcategory: "Cocktail Rings",
    images: [
      "https://via.placeholder.com/300?text=Kundan+Cocktail+Ring+1",
      "https://via.placeholder.com/300?text=Kundan+Cocktail+Ring+2",
      "https://via.placeholder.com/300?text=Kundan+Cocktail+Ring+3",
    ],
    hoverImg: "https://via.placeholder.com/300/FF9A8B?text=Kundan+Cocktail+Ring+Hover",
    description: "Beautiful Kundan cocktail ring for a bold statement.",
    colors: ["#FF9A8B", "#D4A5A5"],
  },
  {
    id: "k-bracelet-cuffs",
    name: "Kundan Cuffs",
    price: "$140",
    category: "Bracelet",
    subcategory: "Cuffs",
    images: [
      "https://via.placeholder.com/300?text=Kundan+Cuffs+1",
      "https://via.placeholder.com/300?text=Kundan+Cuffs+2",
      "https://via.placeholder.com/300?text=Kundan+Cuffs+3",
    ],
    hoverImg: "https://via.placeholder.com/300/FF677D?text=Kundan+Cuffs+Hover",
    description: "Charming Kundan cuffs for a delicate wrist look.",
    colors: ["#FF677D", "#FFB3BA"],
  },
  {
    id: "k-others-mangtika",
    name: "Kundan Mang Tika",
    price: "$50",
    category: "Others",
    subcategory: "Mang Tika",
    images: [
      "https://via.placeholder.com/300?text=Kundan+Mang+Tika+1",
      "https://via.placeholder.com/300?text=Kundan+Mang+Tika+2",
      "https://via.placeholder.com/300?text=Kundan+Mang+Tika+3",
    ],
    hoverImg: "https://via.placeholder.com/300/D4A5A5?text=Kundan+Mang+Tika+Hover",
    description: "Delicate Kundan Mang Tika for traditional ceremonies.",
    colors: ["#D4A5A5", "#FF9A8B"],
  },
  {
    id: "k-others-nath",
    name: "Kundan Nath",
    price: "$75",
    category: "Others",
    subcategory: "Nath",
    images: [
      "https://via.placeholder.com/300?text=Kundan+Nath+1",
      "https://via.placeholder.com/300?text=Kundan+Nath+2",
      "https://via.placeholder.com/300?text=Kundan+Nath+3",
    ],
    hoverImg: "https://via.placeholder.com/300/FF677D?text=Kundan+Nath+Hover",
    description: "Traditional Kundan Nath for a bridal look.",
    colors: ["#FF677D", "#D9BF77"],
  },
  {
    id: "k-others-nose-pin",
    name: "Kundan Nose Pin",
    price: "$40",
    category: "Others",
    subcategory: "Nose Pin",
    images: [
      "https://via.placeholder.com/300?text=Kundan+Nose+Pin+1",
      "https://via.placeholder.com/300?text=Kundan+Nose+Pin+2",
      "https://via.placeholder.com/300?text=Kundan+Nose+Pin+3",
    ],
    hoverImg: "https://via.placeholder.com/300/FFB3BA?text=Kundan+Nose+Pin+Hover",
    description: "Elegant Kundan nose pin for a subtle look.",
    colors: ["#FFB3BA", "#FF677D"],
  },
  {
    id: "k-others-armlets",
    name: "Kundan Armlets",
    price: "$110",
    category: "Others",
    subcategory: "Armlets",
    images: [
      "https://via.placeholder.com/300?text=Kundan+Armlets+1",
      "https://via.placeholder.com/300?text=Kundan+Armlets+2",
      "https://via.placeholder.com/300?text=Kundan+Armlets+3",
    ],
    hoverImg: "https://via.placeholder.com/300/6A0572?text=Kundan+Armlets+Hover",
    description: "Elegant Kundan armlets for ceremonial events.",
    colors: ["#6A0572", "#D9BF77"],
  },

  // Silver Products
  {
    id: "s-necklace-statement",
    name: "Silver Statement Necklace",
    price: "$220",
    category: "Necklace",
    subcategory: "Statement Pieces",
    images: [
      "https://via.placeholder.com/300?text=Silver+Statement+1",
      "https://via.placeholder.com/300?text=Silver+Statement+2",
      "https://via.placeholder.com/300?text=Silver+Statement+3",
    ],
    hoverImg: "https://via.placeholder.com/300/A8D8EA?text=Silver+Statement+Hover",
    description: "Bold silver statement necklace for impactful occasions.",
    colors: ["#A8D8EA", "#FF9A8B"],
  },
  {
    id: "s-earrings-drop",
    name: "Silver Drop Earrings",
    price: "$100",
    category: "Earrings",
    subcategory: "Drop Earrings",
    images: [
      "https://via.placeholder.com/300?text=Silver+Drop+1",
      "https://via.placeholder.com/300?text=Silver+Drop+2",
      "https://via.placeholder.com/300?text=Silver+Drop+3",
    ],
    hoverImg: "https://via.placeholder.com/300/D9BF77?text=Silver+Drop+Hover",
    description: "Elegant silver drop earrings for everyday wear.",
    colors: ["#D9BF77", "#FF677D"],
  },
  {
    id: "s-rings-solitaire",
    name: "Silver Solitaire Ring",
    price: "$150",
    category: "Rings",
    subcategory: "Solitaire Rings",
    images: [
      "https://via.placeholder.com/300?text=Silver+Solitaire+Ring+1",
      "https://via.placeholder.com/300?text=Silver+Solitaire+Ring+2",
      "https://via.placeholder.com/300?text=Silver+Solitaire+Ring+3",
    ],
    hoverImg: "https://via.placeholder.com/300/FF9A8B?text=Silver+Solitaire+Ring+Hover",
    description: "Classic silver solitaire ring for special moments.",
    colors: ["#FF9A8B", "#A8D8EA"],
  },
  {
    id: "s-bracelet-bangles",
    name: "Silver Bangles",
    price: "$120",
    category: "Bracelet",
    subcategory: "Bangles",
    images: [
      "https://via.placeholder.com/300?text=Silver+Bangles+1",
      "https://via.placeholder.com/300?text=Silver+Bangles+2",
      "https://via.placeholder.com/300?text=Silver+Bangles+3",
    ],
    hoverImg: "https://via.placeholder.com/300/FF677D?text=Silver+Bangles+Hover",
    description: "Stylish silver bangles for everyday elegance.",
    colors: ["#FF677D", "#D4A5A5"],
  },
  {
    id: "s-pendants-trendy",
    name: "Silver Trendy Pendant",
    price: "$90",
    category: "Pendants",
    subcategory: "Trendy",
    images: [
      "https://via.placeholder.com/300?text=Silver+Trendy+Pendant+1",
      "https://via.placeholder.com/300?text=Silver+Trendy+Pendant+2",
      "https://via.placeholder.com/300?text=Silver+Trendy+Pendant+3",
    ],
    hoverImg: "https://via.placeholder.com/300/FF9A8B?text=Silver+Trendy+Pendant+Hover",
    description: "Chic silver trendy pendant for a modern style.",
    colors: ["#FF9A8B", "#D4A5A5"],
  },

  // Diamond Products
  {
    id: "d-necklace-choker",
    name: "Diamond Choker Necklace",
    price: "$600",
    category: "Necklace",
    subcategory: "Choker",
    images: [
      "https://via.placeholder.com/300?text=Diamond+Choker+1",
      "https://via.placeholder.com/300?text=Diamond+Choker+2",
      "https://via.placeholder.com/300?text=Diamond+Choker+3",
    ],
    hoverImg: "https://via.placeholder.com/300/FFB3BA?text=Diamond+Choker+Hover",
    description: "Luxurious diamond choker for a regal look.",
    colors: ["#FFB3BA", "#FF9A8B"],
  },
  {
    id: "d-earrings-solitaire",
    name: "Diamond Solitaire Earrings",
    price: "$450",
    category: "Earrings",
    subcategory: "Solitaire",
    images: [
      "https://via.placeholder.com/300?text=Diamond+Solitaire+1",
      "https://via.placeholder.com/300?text=Diamond+Solitaire+2",
      "https://via.placeholder.com/300?text=Diamond+Solitaire+3",
    ],
    hoverImg: "https://via.placeholder.com/300/D4A5A5?text=Diamond+Solitaire+Hover",
    description: "Classic diamond solitaire earrings for timeless beauty.",
    colors: ["#D4A5A5", "#FF9A8B"],
  },
  {
    id: "d-rings-engagement",
    name: "Diamond Engagement Ring",
    price: "$700",
    category: "Rings",
    subcategory: "Engagement Rings",
    images: [
      "https://via.placeholder.com/300?text=Diamond+Engagement+Ring+1",
      "https://via.placeholder.com/300?text=Diamond+Engagement+Ring+2",
      "https://via.placeholder.com/300?text=Diamond+Engagement+Ring+3",
    ],
    hoverImg: "https://via.placeholder.com/300/FF677D?text=Diamond+Engagement+Ring+Hover",
    description: "Sparkling diamond engagement ring to mark special moments.",
    colors: ["#FF677D", "#FFB3BA"],
  },
  {
    id: "d-bracelet-tennis",
    name: "Diamond Tennis Bracelet",
    price: "$500",
    category: "Bracelet",
    subcategory: "Tennis Bracelets",
    images: [
      "https://via.placeholder.com/300?text=Diamond+Tennis+Bracelet+1",
      "https://via.placeholder.com/300?text=Diamond+Tennis+Bracelet+2",
      "https://via.placeholder.com/300?text=Diamond+Tennis+Bracelet+3",
    ],
    hoverImg: "https://via.placeholder.com/300/FF9A8B?text=Diamond+Tennis+Bracelet+Hover",
    description: "Elegant diamond tennis bracelet for a classy look.",
    colors: ["#FF9A8B", "#FF677D"],
  },
  {
    id: "d-others-tiara",
    name: "Diamond Tiara",
    price: "$1200",
    category: "Others",
    subcategory: "Tiara",
    images: [
      "https://via.placeholder.com/300?text=Diamond+Tiara+1",
      "https://via.placeholder.com/300?text=Diamond+Tiara+2",
      "https://via.placeholder.com/300?text=Diamond+Tiara+3",
    ],
    hoverImg: "https://via.placeholder.com/300/D9BF77?text=Diamond+Tiara+Hover",
    description: "Shimmering diamond tiara for a princess-like appeal.",
    colors: ["#D9BF77", "#FF677D"],
  },
];
